apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: production
spec:
  type: {{ .Values.service.type }}
  selector:
    app: worker-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
