apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amansinha24/shopsre-platform.git
    targetRevision: HEAD
    path: helm/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true